version: "3.9"
services:
  rendertron:
    container_name: rendertron
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      # args:
      #   TARGETPLATFORM: linux/arm64  # Pass the build target as an argument
    ports:
      - "3000:3000"
